"use client";

import { useState } from "react";

interface RubricActionsProps {
  onUseThis: () => void;
  isLoading?: boolean;
}

export default function RubricActions({ onUseThis, isLoading = false }: RubricActionsProps) {
  const [autoScoring, setAutoScoring] = useState(true);

  return (
    <div className="space-y-4">
      {/* AI disclaimer banner */}
      <div
        role="alert"
        className="flex gap-3 px-4 py-3 rounded-lg bg-amber-50 border border-amber-200"
      >
        <span className="text-amber-500 mt-0.5 shrink-0" aria-hidden="true">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z" />
            <line x1="12" y1="9" x2="12" y2="13" />
            <line x1="12" y1="17" x2="12.01" y2="17" />
          </svg>
        </span>
        <p className="text-xs text-amber-800 leading-relaxed">
          <span className="font-semibold">AI-Generated Content: </span>
          This content was generated by AI and should be reviewed for accuracy, compliance, and
          alignment with your company&apos;s values and requirements before use.
        </p>
      </div>

      {/* Auto-scoring toggle */}
      <label className="flex items-start gap-3 cursor-pointer group">
        <div className="relative mt-0.5 shrink-0">
          <input
            type="checkbox"
            className="sr-only"
            checked={autoScoring}
            onChange={(e) => setAutoScoring(e.target.checked)}
            aria-describedby="auto-scoring-description"
          />
          <div
            className={`w-9 h-5 rounded-full transition-colors duration-200 ${
              autoScoring ? "bg-[#1A5C4E]" : "bg-gray-300"
            }`}
            aria-hidden="true"
          >
            <div
              className={`absolute top-0.5 left-0.5 w-4 h-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${
                autoScoring ? "translate-x-4" : "translate-x-0"
              }`}
            />
          </div>
        </div>
        <div>
          <p className="text-sm font-semibold text-gray-800 group-hover:text-gray-900">
            Enable Automatic Candidate Scoring
          </p>
          <p id="auto-scoring-description" className="text-xs text-gray-500 mt-0.5 leading-relaxed">
            When enabled, candidate resumes will be automatically scored based on how well they
            match these weighted skills.
          </p>
        </div>
      </label>

      {/* Action buttons */}
      <div className="flex items-center justify-end gap-3 pt-1">
        <button
          type="button"
          className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border-2 border-orange-500 text-orange-600 text-sm font-semibold hover:bg-orange-50 transition-colors focus:outline-none focus:ring-2 focus:ring-orange-500 focus:ring-offset-1"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="14"
            height="14"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
            aria-hidden="true"
          >
            <polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2" />
          </svg>
          Optimize
        </button>

        <button
          type="button"
          onClick={onUseThis}
          disabled={isLoading}
          className="inline-flex items-center gap-2 px-5 py-2 rounded-lg bg-[#1A5C4E] hover:bg-[#154d41] disabled:opacity-60 disabled:cursor-not-allowed text-white text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-[#1A5C4E] focus:ring-offset-1"
        >
          {isLoading ? (
            <>
              <svg
                className="animate-spin"
                xmlns="http://www.w3.org/2000/svg"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
                aria-hidden="true"
              >
                <path d="M21 12a9 9 0 1 1-6.219-8.56" />
              </svg>
              Processing...
            </>
          ) : (
            <>
              Use This
              <span aria-hidden="true">→</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
}
